const routeConstants = {
  ROOT: "/",
  HOME: "/",
  HOW_IT_WORKS: "/how_it_works",
  SELECT: "/select",
  RESUME: "/resume",
  RESUME_CONTACT: "/resume/contact/add",
  RESUME_EDUCATION_LIST: "/resume/education/list",
  RESUME_EDUCATION_TIPS: "/resume/education/tips",
  RESUME_EDUCATION_ADD: "/resume/education/add",
  RESUME_EDUCATION_EDIT: "/resume/education/edit",
  RESUME_WORKHISTORY_TIPS: "/resume/workhistory/tips",
  RESUME_WORKHISTORY_ADD: "/resume/workhistory/add",
  RESUME_WORKHISTORY_LIST: "/resume/workhistory/list",
  RESUME_WORKHISTORY_EDIT: "/resume/workhistory/edit",
  RESUME_SKILL_TIPS: "/resume/skill/tips",
  RESUME_SKILL_ADD: "/resume/skill/add",
  RESUME_SUMMARY_TIPS: "/resume/summary/tips",
  RESUME_SUMMARY_ADD: "/resume/summary/add",
  RESUME_EXTRA_ADD: "/resume/extra/add",
  RESUME_PREVIEW: "/resume/preview",
  PAGE_NOT_FOUND: "/*",
};

export default routeConstants;
